program: rel_classification_info.py
method: grid
parameters:
  seed:
    values: [0,1,2]
  dataset:
    values: ["risec", "japflow", "chemu", "mscorpus"]
  dep:
    values: [0, 1]
  amr:
    values: [0, 1]
command: 
  - ${env}
  - python
  - ${program}
  - --src_dataset
  - ${dataset}
  - --tgt_dataset
  - ${dataset}
  - --seed
  - ${seed}
  - --amr 
  - ${amr}
  - --dep 
  - ${dep}
  - --mode
  - "train"
  - "--domain"
  - "src"
  - "--gnn"
  - "rgcn"
  - "--alpha"
  - "1.0"
  - "--batch_size"
  - "16"
  - "--gnn_depth"
  - "2"
  - "--gpu"
  - "0"